---
- name: Get UUID and device name
  hosts: all
  become: true

  tasks: 
  - name: set mount device name
    set_fact:
      mount_device: "/dev/vda2"

  - name: get UUID of device
    command: blkid -o value -s UUID /dev/vda2
    register: uuid_result

  - name: set fact for UUID
    set_fact:
      mount_uuid: "{{ uuid_result.stdout }}"

