---
- name: Mount device with UUID to /data/speci
  hosts: all
  become: true

  tasks:
    - name: set mount filesystem type
      set_fact: 
        mount_filesystem: "vfat"

    - name: Create /data/speci
      file:
        path: /data/speci
        state: directory
        mode: "0755"

    - name: adding an entry to etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "UUID={{ mount_uuid }} /data/speci vfat defaults 0 0"
        state: present

    - name: Mounting to /data/speci
      shell: mount /data/speci
