- name: Create LVM Caching Disk
  hosts: all
  become: true
  vars:
    lvm_cache_device: /dev/sdb
    lvm_cache_caching_device: /dev/sdc
    lvm_cache_mode: writethrough
    lvm_cache_cache_size: 1G

  roles:
    - rhel-system-roles.storage
